//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientAmountReqByDate
    {
        public int IngredientId { get; set; }
        public System.DateTime ServeDate { get; set; }
        public Nullable<double> RequiredSumAmount { get; set; }
        public string UnitOfMeasure { get; set; }
        public string IngredientName { get; set; }
    }
}
