//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealConsistsOf
    {
        public int Id { get; set; }
        public Nullable<int> MealId { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public Nullable<double> AmountRequired { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
