//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuView
    {
        public int Id { get; set; }
        public int MealId { get; set; }
        public string MealName { get; set; }
        public double Price { get; set; }
        public System.DateTime ServeDate { get; set; }
    }
}
